---
title: "Week4 note"
output: html_document
---
# week4
## Editing Text Variables
### fixing character vectors- `tolower(), toupper()`

```{r}
if(!file.exists("./data")) {dir.create("./data")}
fileUrl <- "https://data.baltimorecity.gov/api/views/dz54-2aru/rows.csv?accessType=DOWNLOAD"
download.file(fileUrl, destfile = "./data/cameras.csv", method = "curl")
cameraData <- read.csv("./data/cameras.csv")
names(cameraData)
```

```{r}
tolower(names(cameraData))
```
### Fixing chararter vectors- `strsplit()`

- good for automatically spliting variable names
- important parameters:x split
```{r}
splitNames <- strsplit(names(cameraData),"\\.")
splitNames[[5]]  # no change
splitNames[[6]]
```
### quick aside- lists
```{r}
mylist <- list(letters = c("A", "b", "c"), numbers = 1:3, matrix(1:25, ncol = 5))
head(mylist)
```
```{r}
mylist[1]
```

```{r}
mylist$letters
```

```{r}
mylist[[1]]
```
### sapply()
```{r}
spiltNames[[6]][1]
firstElement <- function(x){x[1]}
sapply(splitNames, firstElement)
```
### sub()
change _ in rewiews into blank. but just the first _ will be replaced.
`sub("_","",names(reviews),)`
gsub will replace all the _.
`gsub("_", "", "this_is_a_test")`


