library(datasets)
head(airquality)
s  <- split(airquality, airquality$Month)
lapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")]))
x <- rnorm(10)
f1  <- gl(2, 5)
f2 <- gl(5, 2)
str(x)
y <- split(x, list(f1, f2))
